"""Saved-artifact prediction and what-if simulation functions."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import joblib
import pandas as pd

from src.advisory import build_advisory, load_config
from src.data_loader import RAW_FEATURE_COLUMNS
from src.explainability import local_feature_contributions
from src.train import DEFAULT_MODEL_PATH


def load_artifact(model_path: str | Path = DEFAULT_MODEL_PATH) -> dict[str, Any]:
    path = Path(model_path)
    if not path.exists():
        raise FileNotFoundError(f"Model artifact not found: {path}. Run `python -m src.train` first.")
    return joblib.load(path)


def prepare_record(record: dict[str, Any] | pd.Series | pd.DataFrame, metadata: dict[str, Any]) -> pd.DataFrame:
    """Normalize an API, dashboard or CSV record to the model's raw schema."""
    if isinstance(record, pd.DataFrame):
        frame = record.copy()
    elif isinstance(record, pd.Series):
        frame = record.to_frame().T
    else:
        frame = pd.DataFrame([record])
    if "geometry" in frame.columns and ".geo" not in frame.columns:
        frame[".geo"] = frame["geometry"]
    for column in metadata.get("raw_feature_columns", RAW_FEATURE_COLUMNS):
        if column not in frame:
            frame[column] = None
    return frame[metadata.get("raw_feature_columns", RAW_FEATURE_COLUMNS)].copy()


def predict_record(
    artifact: dict[str, Any], record: dict[str, Any] | pd.Series | pd.DataFrame, farm_id: str | None = None
) -> dict[str, Any]:
    metadata = artifact["metadata"]
    model_input = prepare_record(record, metadata)
    prediction = float(artifact["pipeline"].predict(model_input)[0])
    explanation = local_feature_contributions(
        artifact["pipeline"], model_input, metadata["reference_row"]
    )
    farm = farm_id or str(getattr(record, "get", lambda _key, default=None: default)("Farm_ID", "API-input"))
    advisory = build_advisory(
        farm_id=farm,
        predicted_soil_moisture=prediction,
        explanation=explanation,
        model_confidence=float(metadata["relative_confidence_score"]),
        config=load_config(),
    )
    return {"advisory": advisory, "explanation": explanation, "model_name": metadata["model_name"]}


def predict_batch(artifact: dict[str, Any], records: pd.DataFrame) -> pd.Series:
    model_input = prepare_record(records, artifact["metadata"])
    return pd.Series(artifact["pipeline"].predict(model_input), index=records.index, name="Predicted_Soil_Moisture")


def what_if(
    artifact: dict[str, Any], record: dict[str, Any] | pd.Series | pd.DataFrame, changes: dict[str, Any]
) -> dict[str, Any]:
    original = prepare_record(record, artifact["metadata"])
    simulated = original.copy()
    for feature, value in changes.items():
        if feature in simulated.columns:
            simulated.loc[simulated.index[0], feature] = value
    farm_id = str(record.get("Farm_ID", "API-input")) if hasattr(record, "get") else "API-input"
    original_result = predict_record(artifact, original, farm_id=farm_id)
    simulated_result = predict_record(artifact, simulated, farm_id=farm_id)
    original_prediction = original_result["advisory"]["predicted_soil_moisture"]
    simulated_prediction = simulated_result["advisory"]["predicted_soil_moisture"]
    return {
        "simulation": True,
        "simulation_note": "What-if result generated by the saved model; it is not a weather forecast or validated irrigation prescription.",
        "changes": changes,
        "original": original_result,
        "simulated": simulated_result,
        "prediction_change": round(simulated_prediction - original_prediction, 6),
    }

